[package]
name = "scx_stats_derive"
version = "1.0.21"
edition = "2021"
authors = ["Tejun Heo <tj@kernel.org>"]
license = "GPL-2.0-only"
repository = "https://github.com/sched-ext/scx"
description = "Derive macro for scx_stats"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
scx_stats = { path = "..", version = "1.0.22" }
serde_json = "1.0.133"
syn = { version = "2.0", features = ["extra-traits", "full"] }

[lints.clippy]
not_unsafe_ptr_arg_deref = "allow"
