[package]
name = "scxprof"
version = "0.1.0"
edition = "2021"
authors = ["Kumar Kartikeya Dwivedi <memxor@gmail.com>"]
license = "GPL-2.0-only"
repository = "https://github.com/sched-ext/scx"
description = "SCX Workload Profiler"
build = "build.rs"

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.5.28", features = ["derive", "env", "unicode", "wrap_help"] }
ctrlc = "3.1"
libc = "0.2.175"
libbpf-rs = "=0.26.0-beta.1"
log = "0.4.17"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"

[build-dependencies]
scx_cargo = { path = "../../rust/scx_cargo", version = "1.0.25" }
