[package]
name = "scx_p2dq"
version = "1.0.10"
authors = ["Daniel Hodges <hodges.daniel.scott@gmail.com>"]
edition = "2021"
description = "scx_p2dq A simple pick two load balancing scheduler in BPF"
license = "GPL-2.0-only"

[dependencies]
anyhow = "1.0.65"
chrono = "0.4"
clap = { version = "4.1", features = ["derive", "env", "unicode", "wrap_help"] }
crossbeam = "0.8.4"
ctrlc = { version = "3.1", features = ["termination"] }
fb_procfs = "0.7"
lazy_static = "1.5.0"
libbpf-rs = "=0.25.0-beta.1"
libc = "0.2.137"
log = "0.4.17"
ordered-float = "3.4.0"
scx_stats = { path = "../../../rust/scx_stats", version = "1.0.10" }
scx_stats_derive = { path = "../../../rust/scx_stats/scx_stats_derive", version = "1.0.10" }
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.12" }
serde = { version = "1.0.215", features = ["derive"] }
simplelog = "0.12"
sorted-vec = "0.8.3"
static_assertions = "1.1.0"

[build-dependencies]
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.12" }

[features]
enable_backtrace = []
