[package]
name = "scx_layered"
version = "1.0.23"
authors = ["Tejun Heo <htejun@meta.com>", "Meta"]
edition = "2021"
description = "A highly configurable multi-layer BPF / user space hybrid scheduler used within sched_ext, which is a Linux kernel feature which enables implementing kernel thread schedulers in BPF and dynamically loading them. https://github.com/sched-ext/scx/tree/main"
license = "GPL-2.0-only"

[dependencies]
anyhow = "1.0.65"
bitvec = "1.0"
chrono = "0.4"
clap = { version = "4.5.28", features = ["derive", "env", "unicode", "wrap_help"] }
clap_main = "0.2.9"
crossbeam = "0.8.4"
ctrlc = { version = "3.1", features = ["termination"] }
fastrand = "2.1.1"
fb_procfs = "0.7"
inotify = "0.11"
lazy_static = "1.5.0"
libbpf-rs = "=0.26.0-beta.1"
libc = "0.2.175"
regex = "1.11.2"
scx_bpf_compat = { path = "../../../rust/scx_bpf_compat", version = "1.0.20" }
scx_raw_pmu = { path = "../../../rust/scx_raw_pmu", version = "0.1.4" }
scx_stats = { path = "../../../rust/scx_stats", version = "1.0.22" }
scx_stats_derive = { path = "../../../rust/scx_stats/scx_stats_derive", version = "1.0.21" }
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.26" }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "parking_lot", "tracing-log"] }
once_cell = "1.20.2"
walkdir = "2.5"
nvml-wrapper = "0.11.0"
nix = { version = "0.30.1", features = ["sched"] }
sysinfo = "0.35.2"

[build-dependencies]
scx_cargo = { path = "../../../rust/scx_cargo", version = "1.0.27" }

[features]
enable_backtrace = []

[package.metadata.appimage]
auto_link = true
