[package]
name = "scx_simulator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
libbpf-sys = "=1.6.1"
libloading = "0.8"
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
cc = "1.2.29"
