[package]
name = "scx_bpf_unittests"
version = "0.1.6"
edition = "2021"

publish = false

[dependencies]
libbpf-sys = "=1.6.1"  #Â need the includes and can't use libbpf_rs instead

[build-dependencies]
cc = "1.2.29"
indoc = "2.0.5"
object = "0.36.7"
