[package]
name = "vmlinux_docify"
version = "0.1.8"
edition = "2021"
authors = ["Pat S <patso@likewhatevs.io>"]
description = "A tool to annotate vmlinux.h with documentation from kernel sources"

publish = false

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
walkdir = "2.5"
