[package]
name = "scx_lavd"
version = "1.0.5"
authors = ["Changwoo Min <changwoo@igalia.com>", "Igalia"]
edition = "2021"
description = "A Latency-criticality Aware Virtual Deadline (LAVD) scheduler based on sched_ext, which is a Linux kernel feature which enables implementing kernel thread schedulers in BPF and dynamically loading them. https://github.com/sched-ext/scx/tree/main"
license = "GPL-2.0-only"

[dependencies]
anyhow = "1.0.65"
bitvec = { version = "1.0", features = ["serde"] }
clap = { version = "4.1", features = ["derive", "env", "unicode", "wrap_help"] }
crossbeam = "0.8.4"
ctrlc = { version = "3.1", features = ["termination"] }
fb_procfs = "0.7"
hex = "0.4.3"
itertools = "0.13.0"
libbpf-rs = "0.24.1"
libc = "0.2.137"
log = "0.4.17"
ordered-float = "3.4.0"
scx_stats = { path = "../../../rust/scx_stats", version = "1.0.5" }
scx_stats_derive = { path = "../../../rust/scx_stats/scx_stats_derive", version = "1.0.5" }
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.5" }
serde = { version = "1.0", features = ["derive"] }
simplelog = "0.12"
static_assertions = "1.1.0"
plain = "0.2.3"
gpoint = "0.2"

[build-dependencies]
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.5" }

[features]
enable_backtrace = []
