[package]
name = "scx_chaos"
version = "1.0.11"
edition = "2021"

[dependencies]
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.13" }
scx_p2dq = { path = "../../../scheds/rust/scx_p2dq", version = "1.0.12" }

anyhow = "1.0.65"
clap = { version = "4.5.28", features = ["derive", "env", "unicode", "wrap_help"] }
ctrlc = { version = "3.1", features = ["termination"] }
libbpf-rs = "=0.25.0-beta.1"
log = "0.4.17"
simplelog = "0.12"

[build-dependencies]
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.13" }
