[package]
name = "scx_rlfifo"
version = "1.0.11"
authors = ["Andrea Righi <andrea.righi@linux.dev>"]
edition = "2021"
description = "A simple FIFO scheduler in Rust that runs in user-space"
license = "GPL-2.0-only"

[dependencies]
anyhow = "1.0.65"
plain = "0.2.3"
ctrlc = { version = "3.1", features = ["termination"] }
libbpf-rs = "=0.25.0-beta.1"
libc = "0.2.137"
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.14" }
scx_rustland_core = { path = "../../../rust/scx_rustland_core", version = "2.2.10" }

[build-dependencies]
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.14" }
scx_rustland_core = { path = "../../../rust/scx_rustland_core", version = "2.2.10" }

[features]
enable_backtrace = []
