[package]
name = "scx_pandemonium"
version = "5.4.1"
edition = "2021"

[dependencies]
libbpf-rs = { version = "0.26.1", default-features = false }
libc = "0.2"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
ctrlc = { version = "3", features = ["termination"] }
flate2 = "1"
regex = "1"

[dev-dependencies]
libc = "0.2"

[build-dependencies]
scx_cargo = { path = "../../../rust/scx_cargo", version = "1.0.27" }
