[[bin]]
name = "scxctl"

[package]
name = "scxctl"
version = "1.0.10"
edition = "2021"
description = "A cli dbus client for scx_loader"
authors = ["Joe Maples <joe@maples.dev>"]
repository = "https://github.com/sched-ext/scx"
readme = "README.md"
keywords = ["linux", "scx", "scx_scheds", "scx_loader", "sched_ext"]
categories = ["command-line-utilities"]
license = "GPL-2.0-only"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
colored = "3.0.0"
zbus = "5.3.1"
scx_loader = { path = "../../rust/scx_loader" }
