[package]
name = "xtask"
version = "0.1.3"
edition = "2021"

publish = false

[package.metadata.scx]
ci.use_clippy = true

[dependencies]
anyhow = "1.0.100"
cargo_metadata = "0.23"
clap = { version = "4.5.53", features = ["derive"] }
log = "0.4.29"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
simplelog = "0.12"
once_cell = "1.21.3"
toml = "0.8.23"
