[package]
name = "xtask"
version = "0.1.4"
edition = "2021"

publish = false

[package.metadata.scx]
ci.use_clippy = true

[dependencies]
anyhow = "1.0.65"
cargo_metadata = "0.23"
clap = { version = "4.5.28", features = ["derive"] }
log = "0.4.17"
regex = "1.11.2"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
simplelog = "0.12"
once_cell = "1.20.2"
toml = "0.8.19"
