[package]
name = "scxtop"
version = "1.0.21"
edition = "2021"
authors = ["Daniel Hodges <hodges.daniel.scott@gmail.com>", "Yaakov Stein <ymstein14@gmail.com>"]
license = "GPL-2.0-only"
repository = "https://github.com/sched-ext/scx"
description = "sched_ext scheduler tool for observability"

[package.metadata.scx]
ci.use_clippy = true

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = [
    "derive",
    "cargo",
    "wrap_help",
    "unicode",
    "string",
    "unstable-styles",
] }
clap_complete = "4.5.61"
crossterm = { version = "0.28.1", features = ["serde", "event-stream"] }
futures = "0.3.31"
glob = "0.3.3"
libbpf-rs = "=0.26.0-beta.1"
libc = "0.2.178"
log = "0.4.29"
num-format = { version = "0.4.4", features = ["with-serde", "with-system-locale"] }
perfetto_protos = "0.51.1"
plain = "0.2.3"
procfs = "0.15.1"
protobuf = "3.7.2"
rand = "0.8.5"
ratatui = { version = "0.29.0", features = ["serde", "macros"] }
regex = "1.12.2"
scx_stats = { path = "../../rust/scx_stats", version = "1.0.20" }
scx_utils = { path = "../../rust/scx_utils", version = "1.0.25" }
simplelog = "0.12"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
signal-hook = "0.3.18"
sysinfo = "0.35.2"
tokio-util = "0.7.17"
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.8.23"
xdg = "2.5.2"
log-panics = { version = "2", features = ["with-backtrace"]}
hashbrown = "0.15.5"
smartstring = { version = "1.0.1", features = ["serde"] }
nix = { version = "0.30.1", features = ["time", "user"] }
blazesym = "0.2.1"
rayon = "1.11"

[dev-dependencies]
criterion = "0.6.0"
tempfile = "3.23.0"

[[bench]]
name = "search_benchmark"
harness = false

[build-dependencies]
scx_stats = { path = "../../rust/scx_stats", version = "1.0.20" }
scx_cargo = { path = "../../rust/scx_cargo", version = "1.0.25" }
