[package]
name = "scxtop"
version = "1.0.8"
edition = "2021"
authors = ["Daniel Hodges <hodges.daniel.scott@gmail.com>"]
license = "GPL-2.0-only"
repository = "https://github.com/sched-ext/scx"
description = "sched_ext scheduler tool for observability"

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.1", features = [
    "derive",
    "cargo",
    "wrap_help",
    "unicode",
    "string",
    "unstable-styles",
] }
libbpf-rs = "=0.24.8"
scx_utils = { path = "../../rust/scx_utils", version = "1.0.8" }
config = "0.14.1"
crossterm = { version = "0.28.1", features = ["serde", "event-stream"] }
derive_deref = "1.1.1"
directories = "5.0.1"
futures = "0.3.31"
json5 = "0.4.1"
lazy_static = "1.5.0"
libc = "0.2.137"
log = "0.4.17"
perf-event-open-sys = "4.0.0"
plain = "0.2.3"
ratatui = { version = "0.29.0", features = ["serde", "macros"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
signal-hook = "0.3.17"
strip-ansi-escapes = "0.2.0"
tokio = { version = "1.42.0", features = ["full"] }
tokio-util = "0.7.13"
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "serde"] }

[build-dependencies]
scx_utils = { path = "../../rust/scx_utils", version = "1.0.8" }
