name: bpf-next-test

on:
  # only runs on main, every 6 hours. specify hours explicitly so scheduled runs can be offset and use a random minute.
  schedule:
    - cron: "35 0,6,12,18 * * *"

jobs:
  build-kernel:
    uses: ./.github/workflows/build-kernel.yml
    with:
      repo-name: bpf/bpf-next

  integration-test:
    uses: ./.github/workflows/integration-tests.yml
    needs: build-kernel
    with:
      repo-name: bpf/bpf-next

  notify-job:
    runs-on: ubuntu-latest
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    needs:
      - integration-test
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: ci
        SLACK_ICON: https://www.dictionary.com/e/wp-content/uploads/2018/03/thisisfine-1.jpg
        SLACK_TITLE: Workflow failed
        SLACK_MESSAGE: bpf-next ci job failed.
        SLACK_COLOR: failure
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}


