name: stable-test

on:
  # only runs on main, every 6 hours. specify hours explicitly so scheduled runs can be offset and use a random minute.
  schedule:
    - cron: "40 2,8,14,20 * * *"

jobs:
  build-kernels:
    uses: ./.github/workflows/build-kernels.yml
    secrets: inherit

  integration-test:
    uses: ./.github/workflows/integration-tests.yml
    needs: build-kernels
    secrets: inherit
    with:
      repo-name: stable/linux-rolling-stable

  e2e-test:
    uses: ./.github/workflows/e2e-tests.yml
    needs: build-kernels
    secrets: inherit
    with:
      repo-name: stable/linux-rolling-stable

  notify-job:
    runs-on: ubuntu-latest
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    needs:
      - integration-test
      - e2e-test
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: ci
        SLACK_ICON: https://www.dictionary.com/e/wp-content/uploads/2018/03/thisisfine-1.jpg
        SLACK_TITLE: Workflow failed
        SLACK_MESSAGE: stable ci job failed.
        SLACK_COLOR: failure
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

