[package]
name = "scxcash"
version = "0.1.4"
edition = "2021"
authors = ["Kumar Kartikeya Dwivedi <memxor@gmail.com>"]
license = "GPL-2.0-only"
repository = "https://github.com/sched-ext/scx"
description = "Cache Usage Analyzer for sched_ext Schedulers"
build = "build.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive", "env", "unicode", "wrap_help"] }
log = "0.4.29"
libc = "0.2.178"
libbpf-rs = "=0.26.0-beta.1"
scx_utils = { path = "../../rust/scx_utils", version = "1.0.25" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
simplelog = "0.12"
ctrlc = "3.5"
num_cpus = "1.17"

[build-dependencies]
scx_cargo = { path = "../../rust/scx_cargo", version = "1.0.25" }
